apply plugin: 'com.android.application'

if (project.hasProperty("coxswain-private") && new File(project.property("coxswain-private")).exists()) {
    apply from: project.property("coxswain-private")
}

android {
    namespace 'svenmeier.coxswain'
    compileSdk 35

    buildFeatures {
        buildConfig true
    }

    defaultConfig {
        applicationId "svenmeier.coxswain"
        minSdk 21
        multiDexEnabled true
        targetSdk 34

        versionCode Integer.parseInt(project.property("coxswain-versionCode"))
        versionName project.property("coxswain-versionName")
    }
    buildTypes {
        debug {
            debuggable true
        }
        release {
            debuggable false
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    productFlavors {
    }
}

ext {
    supportLibraryVersion = '1.3.0'
    playFitServicesVersion = '21.1.0'
    playAuthServicesVersion = '21.0.0'
}

dependencies {
    implementation 'androidx.multidex:multidex:2.0.1'
    implementation files('aars/antpluginlib_3-8-0.aar')
    implementation "androidx.gridlayout:gridlayout:1.0.0"
    implementation 'com.google.android.material:material:1.11.0'
    implementation 'androidx.preference:preference:1.2.1'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation "com.google.android.gms:play-services-fitness:$playFitServicesVersion"
    implementation "com.google.android.gms:play-services-auth:$playAuthServicesVersion"
    implementation 'com.github.PhilJay:MPAndroidChart:v3.1.0'
    testImplementation 'junit:junit:4.13.2'
    implementation project(':propoid-core')
    implementation project(':propoid-db')
    implementation project(':propoid-ui')
    implementation project(':propoid-util')
}
